version: '3.8'

services:
  api:
    build: .
    container_name: addressapp-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - PORT=8080
      - ConnectionStrings__DefaultConnection=User Id=postgres.cztqtxivdrkibtkczdrt;Password=Meryus.2855;Server=aws-1-eu-central-1.pooler.supabase.com;Port=5432;Database=postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s