[
build
]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/.next"

[[
plugins
]]
  package = "@netlify/plugin-nextjs"

[
build.environment
]
  NODE_VERSION = "22"
  NEXT_PUBLIC_API_URL = "https://addressapp-api-1012108375831.europe-west1.run.app/api"